#!/usr/bin/env bash

# setup required packages
sudo apt update
sudo apt install -y \
    vim \
    python3-gi \
    python3-flask \
    python3-yaml \
    gir1.2-gst-rtsp-server-1.0 \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-tools \
    gstreamer1.0-alsa \
    gstreamer1.0-omx \
    ntp \
    ntpdate

if [ "$(grep BCM2835 /proc/cpuinfo)" != "" ]; then
    # ensure v4l2 can load the pi camera
    echo 'bcm2835-v4l2' | sudo tee /etc/modules-load.d/pi_camera_module.conf

    if [ "$(grep iwconfig /etc/rc.local)" == "" ]; then
        # disable wlan0 power management for better latency
        sudo sed -i '$iiwconfig wlan0 power off' /etc/rc.local
    fi

    if [ "$(grep tvservice /etc/rc.local)" == "" ]; then
        # turn off power to hdmi to save a bit of power
        sudo sed -i '$itvservice -o' /etc/rc.local
    fi

    # crank up cpu freq
    #sudo sh -c "echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"
fi

# put the rtsp server script in /opt
sudo cp picam.py /opt/picam.py

# copy over configuration
if [ -f 'picam.yaml' ]; then
    sudo cp picam.yaml /opt/picam.yaml
fi

# load the picamera/webcam rtsp service
sudo cp services/picam.service /lib/systemd/system/picam.service
sudo systemctl daemon-reload

# run the service on startup
sudo systemctl enable picam.service

# copy over the picam-ctl service code
sudo cp -r picam-ctl/ /opt/

# load the webcam control service
sudo cp services/picam-ctl.service /lib/systemd/system/picam-ctl.service
sudo systemctl daemon-reload

# run the service on startup
sudo systemctl enable picam-ctl.service
